In [10]:
d = '''{
"Name" : "Shubham Rawat",
"Email" : "Rawatshubham@gmail.com",
"Experience" : ["ML","DL","Flask","Python"],
"Tech" : ["test1","test2","test3","test4"],
"address" : "Roorkee"
}

'''

In [2]:
import pandas as pd


In [11]:
pd.read_json(d)

Name                   Email Experience   Tech  address
0  Shubham Rawat  Rawatshubham@gmail.com         ML  test1  Roorkee
1  Shubham Rawat  Rawatshubham@gmail.com         DL  test2  Roorkee
2  Shubham Rawat  Rawatshubham@gmail.com      Flask  test3  Roorkee
3  Shubham Rawat  Rawatshubham@gmail.com     Python  test4  Roorkee

In [1]:
import numpy as np

In [4]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
5 + np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
np.empty((3,6))

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306,
        1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306,
        1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307,
        9.34609790e-307, 3.91792279e-317, 8.34424766e-308]])

In [16]:
#we can generate many no. between 2 no.
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [19]:
np.linspace(2,6).reshape(5,10)

array([[2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
        2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388],
       [2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
        3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041],
       [3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
        4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694],
       [4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
        4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347],
       [5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
        5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ]])